apiVersion: v1
kind: ConfigMap
metadata:
  name: config1
  namespace: default
data:
  name: web1
  ip: 192.168.1.101
  nginx-conf: |
    server {
      servername www.bbb.com;
      listen 80;
      location / {
        root /usr/share/nginx/html1;
      }
    }

