apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      #volumes:
      #- name: datavol
      #  persistentVolumeClaim: 
      #    claimName: nfs-pvc1
      volumes:
      - name: datavol
        hostPath: 
          path: /data/nginx
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: http
          containerPort: 80
          #hostPort: 81
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: datavol
        imagePullPolicy: IfNotPresent
