apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
      - name: datavol
        hostPath:
          path: /data/xlpsystem/mariadb
      containers:
      - name: mariadb
        image: mariadb:10.3
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: datavol
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'W2qgpsLtQt'
