apiVersion: v1
kind: ReplicationController
metadata:
  name: parsoid
spec:
  replicas: 1
  selector:
    app: parsoid
  template:
    metadata:
      labels:
        app: parsoid
    spec:
      containers:
      - name: parsoid
        image: thenets/parsoid:0.9.0
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
        env:
        - name: PARSOID_DOMAIN_localhost
          value: 'http://mediawiki/api.php'
