apiVersion: v1
kind: ReplicationController
metadata:
  name: phabricator
spec:
  replicas: 1
  selector:
    app: phabricator
  template:
    metadata:
      labels:
        app: phabricator
    spec:
      volumes:
      - name: repovol
        hostPath: 
          path: /data/xlpsystem/phabricator/repos
      - name: extvol
        hostPath:
          path: /data/xlpsystem/phabricator/extensions
      containers:
      - name: phabricator
        image: redpointgames/phabricator
        ports:
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        - containerPort: 80
          name: outer
        volumeMounts:
        - mountPath: /repos
          name: repovol
        - mountPath: /data/phabricator/phabricator/src/extensions
          name: extvol
        env:
        - name: "MYSQL_HOST"
          value: "phabricator-mysql"
        - name: "MYSQL_USER"
          value: "root"
        - name: "MYSQL_PASS"
          value: "phabricator"
        - name: "PHABRICATOR_REPOSITORY_PATH"
          value: "/repos"
        - name: "PHABRICATOR_HOST"
          value: "dev.bjth:30005"
        - name: "ENABLE_APCU"
          value: "true"
        imagePullPolicy: IfNotPresent
