apiVersion: v1
kind: ReplicationController
metadata:
  name: phabricator-mysql
spec:
  replicas: 1
  selector:
    app: phabricator-mysql
  template:
    metadata:
      labels:
        app: phabricator-mysql
    spec:
      volumes:
      - name: datavol
        hostPath:
          path: /data/xlpsystem/phabricator/data/mysql
      - name: configvol
        hostPath:
          path: /data/xlpsystem/phabricator/config/mysql
      containers:
      - name: phabricator-mysql
        image: mysql:5.7.14
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: datavol
        - mountPath: /etc/mysql
          name: configvol
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'phabricator'
