apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nginx
  labels:
    type: pv
    sys: test
    pv: nginx
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs: 
    path: /nfs/data/test
    server: 192.168.1.101
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nginx
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests: 
      storage: 1Gi
  storageClassName: nfs
  selector:
    matchLabels:
      type: pv
      sys: test
      pv: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      type: app
      sys: test
      app: nginx
  template:
    metadata:
      labels:
        type: app
        sys: test
        app: nginx
    spec:
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: nfs-nginx
      containers:
      - name: nginx
        image: nginx
        ports:
        - name: outer
          containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: pv-data
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  type: NodePort
  ports:
  - name: outer
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    type: app
    sys: test
    app: nginx

