apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: default
spec:
  ports:
  - name: outer
    port: 3306
  selector:
    type: app
    sys: xlpsystem
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app
      sys: xlpsystem
      app: mariadb
  template:
    metadata:
      labels:
        type: app
        sys: xlpsystem
        app: mariadb
    spec:
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: nfs-xlpsystem-mariadb
      containers:
      - name: mariadb-container
        image: mariadb:10.3
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: pv-data
        imagePullPolicy: IfNotPresent
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: 'W2qgpsLtQt'

