apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  namespace: default
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31001
  selector:
    type: app
    sys: xlpsystem
    app: mediawiki
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      type: app
      sys: xlpsystem
      app: mediawiki
  template:
    metadata:
      labels:
        type: app
        sys: xlpsystem
        app: mediawiki
    spec:
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: nfs-xlpsystem-mediawiki
      - name: pv-dev
        persistentVolumeClaim:
          claimName: nfs-xlpsystem-mediawiki-dev
      containers:
      - name: mediawiki-container
        image: xlpsystem/mediawiki:20180827140844
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /xlp_data
          name: pv-data
        - mountPath: /xlp_dev
          name: pv-dev
        imagePullPolicy: IfNotPresent

